{
	"version": "0.9.4.0",
	"changelog": "ADDED NEED STEAM AND IP TO THE CONFIG, NEW CONNECTING CARD, NEW DETECTIONS FOR: NOCLIP, NO RELOAD, TELEPORT TO WAYPOINT, ANTI EULEN FREECAM AND NOCLIP, ANTI SUSANO KILL, ANTI SUSANO SAFE EXPLODE, ANTI SUSANO RAGDOLL EVERYONE, AIMBOT, CAR AND PEDS SPAM, MAX CARS SPEED UNTIL BAN, FIXED: SOLO SESSION AND SILENT AIM, WORKING ON: ANTI TRIGGER"
}
